#!/bin/bash

function download {
    mkdir -p ~/.cache/plasmaphone/ && cd ~/.cache/plasmaphone/
    # download cyanogenmod
    wget -c http://neon.plasma-mobile.org/cm-stripped.zip
    wget -c http://neon.plasma-mobile.org/twrp-3.0.2-0-hammerhead.img
    md5sum ~/.cache/plasmaphone/twrp-3.0.2-0-hammerhead.img
}

function flash-phone {
    echo "Waiting for device to be in the fastboot mode"
    fastboot getvar product

    echo "Flashing recovery"
    fastboot format cache
    fastboot flash recovery ~/.cache/plasmaphone/twrp-3.0.2-0-hammerhead.img
    fastboot boot ~/.cache/plasmaphone/twrp-3.0.2-0-hammerhead.img

    sleep 10
    echo "Flashing cyanogenmod now"
    adb push ~/.cache/plasmaphone/cm-stripped.zip /cache/cm.zip
    echo "--update_package=/cache/cm.zip" > /tmp/command
    adb push /tmp/command /cache/recovery/command

    adb reboot recovery
    adb wait-for-device

    echo "Done flashing cyanogenmod, now flashing rootfs and lxc"
}

download
flash-phone
